### ISSUE TITLE
Clarification of use of the library and tools needed in addition to info page.

### ISSUE THREAD

**Issue by Netoperz** [wavesoft/CCLib#2]
Hello,
I would like to ask a few i think simple and probably dummy questions to be sure what can I expect:
1. The library makes the arduino CC Debugger hardware (alike) if you do not have one around and can be used as programmer/flasher for firmware files for CC2540 BT4.0 modules , and it doesn't mather what is the actual vendor of the PCB, for example can I use it to flash new firmware to HC-08 BLE module from china http://des.everbuying.net/uploads/2015/201507/heditor/201507280914003477.JPG ?
2. If i would like to write a firmware there is a boot loader to flash, and firmware, and can I flash both with this scripts ?

I'm asking because all references are for "real" cc debugger, and i do not have one around i have bought one but it will come to me in 4 days, and i must flash a HC-08 with a specific firmware for my prototype for tomorrow otherwise someone will cut my head off because of delay.....

http://www.dfrobot.com/wiki/index.php?title=How_to_flash_a_new_CC2540_chip_with_DFRobot_BLE_service%3F

Any help and instructions will be appreciated 

Cheers
:/

**Comment by wavesoft** [comment]
Hello @Netoperz, 

> 1. The library makes the arduino CC Debugger hardware (alike) if you do not have one around and can be used as programmer/flasher for firmware files for CC2540 BT4.0 modules , and it doesn't mather what is the actual vendor of the PCB, for example can I use it to flash new firmware to HC-08 BLE module from china http://des.everbuying.net/uploads/2015/201507/heditor/201507280914003477.JPG ?

You are correct the Arduino sketch will make your board able to communicate with the CC2540 chip. You just need to wire your arduino accordingly to the `DD`, `DC` and `RST` pins and you are ready to go.

> If i would like to write a firmware there is a boot loader to flash, and firmware, and can I flash both with this scripts ?

I didn't completely understand what you are trying to do here. The CC Debug protocol allows you to flash whatever part of memory you want, from completely overwriting the entire memory to just updating the bootloader or the program that gets executed. However my python scripts are quite simple and will just replace the entire program memory with the contents of the hex file you specified, so make sure what you are trying to flash contains both bootloader and program memory.

Just to be safe you can first create a back-up (and also test if your set-up works correctly):

```
./cc_read_flash.py --port=<serial port> --out=backup.hex
```

**Comment by Netoperz** [comment]
Thank You for response, That is what i was afraid while reading the info about use of this software.
If You can, you may add that short info about need of containing the loader for example and the firmware in one file. Because most software dedicated for CC debugger is capable of writing only a part of the memory that you need, so you can flash only boot loader for example.

In my case i have to change functionality of the BLE module that i have from different project (a few boards of HC-08 Bluetooth 4.0) but that boards do not support HID in their firmware, so i have to flash a different firmware with HID functionality, and that firmware is splited in two parts, one is boot loader for module, second part is actual program. Because that files were prepared for use with native tools for cc debugger. 
I'm waiting for package with HID modules, and debugger to arrive from china but it will take some time, and I need to build 3 prototypes, so that's the reason of looking in to your tools.

Maby i'll try to flash the boot loader first and than i'll try to flash the firmware (program) over the UART, it should be fine that way.

**Comment by wavesoft** [comment]
Well, note that the python scripts are just some reference implementation of the `CCLib` library. In principle you can have full control over the chip with the `python/cclib` library. 

For example, I just updated the `cc_write_flash.py` script and made the full chip erase an optional feature. You can now use it to flash only the region you are interested in.

Keep in mind though that the memory offset is specified in the .hex file, but if you want it's very easy to add an `offset` parameter to the flash write script in order to shift the memory addresses.

**Comment by wavesoft** [comment]
Hello @Netoperz!  I don't know if you had any luck using this scripts, but just to let you know, I have updated lot's of pieces in the code, including an offset parameter that you can use to program arbitrary code regions (not tested though)!

If you are still interested in using this project let me know of your results!

**Comment by Netoperz** [comment]
Hello, i will test the code today, i was so freaking busy, and the project with BT4.0 was a bit delayed (on the client side) so i dropped playing wit it and took the things with first priority to finish. Now i have got most done so i can take over BLE part.

I'll check the new source and i'll try to use it on my chip. 
This tool you are providing is a very useful thing, and now the BLE 4.0 is getting more popular and not always for starting you got debugger around. sooner or later every one will buy one, because tre price is quite low even for original one (in Poland original costs about 40 EUR, in china you can get it for 20$ including shipping) but if you got arduino, and you need just to check what it is all about.... well this software programmer is a bless. And as far as i know there is no other project like this around.
So thank you very much for your effort and work. And if you will ever be in Cracow in poland I own you a beer :)

I'll post results later.
You should look on the CC2541 support too because now it is more common version of IC.
