### ISSUE TITLE
showing error in __init__.py

### ISSUE THREAD

**Issue by vprithiviraj** [wavesoft/CCLib#4]
![untitled](https://cloud.githubusercontent.com/assets/16076201/19110586/71d3f1ce-8b18-11e6-8a64-676907a1ab0a.png)
while trying to debug the CC2541 chip from the terminal i change into the folder which is having that source files and i ran the 
    CC_info.py COM11
  from the cmd prompt terminal. then it was showing the paranthesis error for print functions inside the source files, then i cleared all those errors now clearing all those error, one more error came like for 
     k,v in kwargs.iteritems():
     attributeerror:'dict' object has no attribute 'iteritems'

**Comment by wavesoft** [comment]
Hello @vprithiviraj , I guess this was due to wrong Python version? Assuming that at least you got pass by this problem judging by your comment on #5 .

**Comment by vprithiviraj** [comment]
nope still both the problems persists. on #5 i commented the line which was making the attribute error.
  that is the line 60 of **init**.py. I'm using python34. is there any recommemded version is available for this project?

thanks in advance

**Comment by wavesoft** [comment]
Yes, unfortunately this code is not yet compatible with python 3.x (they have changed a couple of things and the new versions are not backwards-compatible). So I guess you tried python 2.7 on #5 and you got this encoding error, right? I will have a look.

**Comment by wavesoft** [comment]
Hey @vprithiviraj , I am not sure if you have fixed your problem, but I now added Python3 support to the project. Feel free to re-open this issue if you have further problems.
